### PR TITLE
Add "gdb-python" and "libkdumpfile" dependencies

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
```
± git-ab-pre-push -v internal-qa -p aws --artifacts ALL --test-upgrade-from trunk --upgrade-to-variant internal-qa --upgrade-test-dcenter-host dlpxdc.co
Detected linux-pkg package: delphix-platform
Waiting for build to start...
Your build is at: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1053/
```

**Comment by prakashsurya** [comment]
Due to the issues we're having in DCOA, I manually built the "gdb-python", "libkdumpfile" and "delphix-platform" (with this change) packages and installed them on a trunk VM:
```
$ sudo apt-get install ./delphix-platform-esx_2019.05.14.17_amd64.deb ./gdb-python_1.0.0-delphix-2019.05.14.17_amd64.deb ./libkdumpfile_1.0.0-delphix-2019.05.14.17_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'delphix-platform-esx' instead of './delphix-platform-esx_2019.05.14.17_amd64.deb'
Note, selecting 'gdb-python' instead of './gdb-python_1.0.0-delphix-2019.05.14.17_amd64.deb'
Note, selecting 'libkdumpfile' instead of './libkdumpfile_1.0.0-delphix-2019.05.14.17_amd64.deb'
The following packages were automatically installed and are no longer required:
  libbabeltrace1 libc6-dbg
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  gdb gdbserver
The following NEW packages will be installed:
  gdb-python libkdumpfile
The following packages will be upgraded:
  delphix-platform-esx
1 upgraded, 2 newly installed, 2 to remove and 0 not upgraded.
Need to get 0 B/4,005 kB of archives.
After this operation, 3,227 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /tmp/delphix-platform-esx_2019.05.14.17_amd64.deb delphix-platform-esx amd64 2019.05.14.17 [17.9 kB]
Get:2 /tmp/gdb-python_1.0.0-delphix-2019.05.14.17_amd64.deb gdb-python amd64 1.0.0-delphix-2019.05.14.17 [3,747 kB]
Get:3 /tmp/libkdumpfile_1.0.0-delphix-2019.05.14.17_amd64.deb libkdumpfile amd64 1.0.0-delphix-2019.05.14.17 [239 kB]
(Reading database ... 155260 files and directories currently installed.)
Removing gdbserver (8.1-0ubuntu3) ...
(Reading database ... 155255 files and directories currently installed.)
Preparing to unpack .../delphix-platform-esx_2019.05.14.17_amd64.deb ...
+ case $1 in
+ systemctl disable delphix-migration.service
+ systemctl disable delphix-platform.service
Removed /etc/systemd/system/default.target.wants/delphix-platform.service.
+ rm -f /var/lib/delphix-platform/ansible-done
+ exit 0
Unpacking delphix-platform-esx (2019.05.14.17) over (1.0.0-delphix-2019.05.10.03) ...
(Reading database ... 155252 files and directories currently installed.)
Removing gdb (8.1-0ubuntu3) ...
Selecting previously unselected package gdb-python.
(Reading database ... 155174 files and directories currently installed.)
Preparing to unpack .../gdb-python_1.0.0-delphix-2019.05.14.17_amd64.deb ...
Unpacking gdb-python (1.0.0-delphix-2019.05.14.17) ...
Selecting previously unselected package libkdumpfile.
Preparing to unpack .../libkdumpfile_1.0.0-delphix-2019.05.14.17_amd64.deb ...
Unpacking libkdumpfile (1.0.0-delphix-2019.05.14.17) ...
Setting up gdb-python (1.0.0-delphix-2019.05.14.17) ...
Processing triggers for install-info (6.5.0.dfsg.1-2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up libkdumpfile (1.0.0-delphix-2019.05.14.17) ...
Setting up delphix-platform-esx (2019.05.14.17) ...
+ case $1 in
+ systemctl enable auditd.service
Synchronizing state of auditd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable auditd
+ systemctl enable delphix-migration.service
Created symlink /etc/systemd/system/default.target.wants/delphix-migration.service → /lib/systemd/system/delphix-migration.service.
+ systemctl enable delphix-platform.service
Created symlink /etc/systemd/system/default.target.wants/delphix-platform.service → /lib/systemd/system/delphix-platform.service.
+ systemctl enable systemd-networkd.service
+ id -u postgres
++ id -u postgres
+ [[ 65437 -ne 65437 ]]
+ exit 0
Processing triggers for libc-bin (2.27-3ubuntu1) ...
```

**Comment by prakashsurya** [comment]
> pending ab-pre-push

I can't get a clean pre-push run with the DCOA issues, so I'm going to go ahead and push this. If we find it to be problematic, it's a simple revert.

bors r+

**Comment by pzakha** [comment]
> I can't get a clean pre-push run with the DCOA issues, so I'm going to go ahead and push this. If we find it to be problematic, it's a simple revert.

I definitely disagree with this approach. Why bother testing anything before pushing since every is a simple revert?

**Comment by prakashsurya** [comment]
> I definitely disagree with this approach.

Let's agree to disagree. I'm confident in this change.

With that said, I welcome the addition of automatic testing that'll prevent pushing commits without passing tests; like I've started doing for appliance-build.

**Comment by pzakha** [comment]
I just fail to see why the need to do this push right now, rather than delaying it until a successful run of ab-pre-push. If we had automatic testing that would prevent pushing commits without passing tests then you would not be able to push this right now, so it seems to me like not pushing would be the better course of action.

In general, I can list a few reasons to push without testing:
 - The change is trivial and the chance of it breaking anything is very low.
 - The build is currently broken and the push aims to fix the build, so as to unblock the rest of the team.
 - The change was already tested, but we are adding some trivial changes to it. Re-running the tests would take significant time / resources.
 - The change is trivial and needs to be pushed to unblock other time sensitive work.

While this change is most likely not going to break anything, if it does cause breakage then appliance-build will be failing. If several people decide to push untested changes while the build is broken due to infrastructure issues, then once the infrastructure issues are resolved we may have more downtime as untested breaking changes were introduced by some of those changes.

This change doesn't look time sensitive, so I'm curious about your motivations to rush pushing it.

**Comment by prakashsurya** [comment]
> In general, I can list a few reasons to push without testing

To be clear, I did not push without testing. I tested this change by manually building the packages and installing them on a trunk VM.

> The change is trivial and the chance of it breaking anything is very low.

Is this change not trivial with a low chance of breaking anything?

> If several people decide to push untested changes while the build is broken due to infrastructure issues, then once the infrastructure issues are resolved we may have more downtime as untested breaking changes were introduced by some of those changes.

Right, this is why I advocate for automated required testing.

Since we don't have that, the existing culture/precedence is to hold the developer accountable for running the tests that need to be run to test their changes, which I did.

> This change doesn't look time sensitive, so I'm curious about your motivations to rush pushing it.

IMO, the change was tested and ready to land, so why wait?

**Comment by basil** [comment]
This debate seems more semantic than substantive. This issue is the meaning of “testing.” @pzakha seems to be referring only to end-to-end automated testing, while @prakashsurya is referring to all forms of testing (including manually exercising the code under test).

My substantive position is that understanding the _context(s)_ in which the code under test runs is key to performing sufficient testing. Merely exercising the code under test manually isn't necessarily sufficient if that code was exercised in an unrealistic context. On the other hand, even end-to-end automated testing is only sufficient if it exercises the code under test in the relevant context(s).

**Comment by pzakha** [comment]
I've re-read the conversation and it looks like I've missed the part where Prakash did the manual testing by installing delphix-platform with the dependencies, so apologies for missing that bit on context. I agree that given the testing that was done it was fine pushing at this point. I had only read the last post from Prakash that I got in my email notification, which is what I had concerns with:
> I can't get a clean pre-push run with the DCOA issues, so I'm going to go ahead and push this. If we find it to be problematic, it's a simple revert.

This gave me the impression that testing that Prakash was deeming necessary at first was being abandoned because of DCOA issues, and that a revert would be a normal course of action in case of issues due to the abandoned tests. This was a misunderstanding on my behalf.

With all this said, when there are temporary infrastructure issue that prevent me from doing the testing I want, I rather wait for the infrastructure issues to clear up before pushing unless there are other reasons that require for to push earlier. It's not something that we mandate, but rather that's my personal approach for minimizing potential disruption.

**Pull request merged**
