### PR TITLE
DLPX-81199 don't run zfs-mount service within upgrade container

### PR DESCRIPTION
**Pull request by prakashsurya**
Note, this depends on http://reviews.delphix.com/r/81395/ landing first.

### CODE REVIEW

**Comment by sebroy** [comment]
In the product, upgrade verification relies on domain0 filesystems being present in the container, right (specifically `/mds`, which is in the domain0 pool)?

**Comment by prakashsurya** [comment]
> (specifically /mds, which is in the domain0 pool)?

ah, right.. presumably the upgrade testing is going to catch that.. I think it might be better to mount `domain0/mds` specifically, rather than everything from `domain0`.. I think the mounting everything approach, also adds latency upgrade verification when it's run on customer systems with lots of VDBs/etc..

so, yea, I think this change as is might not be enough.. I'll think about where/how to mount `domain0/mds` (assuming that's not handled already in some other script)..

**Comment by prakashsurya** [comment]
@sebroy I've opened http://reviews.delphix.com/r/81395/ to address your concern; it looks like that is all that's needed for the upgrade verification clone of postgres to work with the changes being proposed in this PR.

**Review by dbj-delphix — APPROVED** [review]
This LGTM

**Comment by prakashsurya** [comment]
See #375

**Comment by prakashsurya** [comment]
I seem to have dropped the ball on this.. re-opening here: https://github.com/delphix/delphix-platform/pull/465

**Pull request closed without merging**
