### PR TITLE
DLPX-74315 Conflicts between GCP agent packages

### PR DESCRIPTION
**Pull request by grwilson**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by grwilson** [comment]
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4926/

The deployed image:
```
root@gwilson-gcpfix:~# apt list --installed google*
Listing... Done
google-compute-engine/now 20201222.00-0ubuntu2~18.04.0 all [installed,local]
google-compute-engine-oslogin/now 20210122.00-0ubuntu1~18.04.0 amd64 [installed,local]
google-guest-agent/now 20201217.02-0ubuntu1~18.04.0 amd64 [installed,local]
```

**Comment by pzakha** [comment]
Have you tested this with our current/latest linux-package-mirror on master? I.e. will it require a flag day where we need to post this review and update the mirror at the same time?

Also, can you run ab-pre-push with integration tests & upgrade tests?

**Comment by grwilson** [comment]
> Have you tested this with our current/latest linux-package-mirror on master? I.e. will it require a flag day where we need to post this review and update the mirror at the same time?
> 
> Also, can you run ab-pre-push with integration tests & upgrade tests?

Yes, I ran it with the current mirror and it fails to build: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4927/

So we will need to update the mirror and then push this change.

I kicked off a testing build with the mirror in the bug and testing enabled: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4929/

**Review by pzakha — APPROVED** [review]
LGTM, pending testing and an update of the mirror on master.

**Comment by grwilson** [comment]
Spoke with Garrett and our plan will be as follows:

- manually update master's mirror
- integrate this change
- manually update 6.0/stage mirror
- integrate the backport
- and finally revert the devops change to re-enable mirror syncs.

**Review by prakashsurya — APPROVED** [review]

**Pull request merged**
