### PR TITLE
DLPX-81199 don't run zfs-mount service within upgrade container

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
- `git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/7110/) and [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/7120/)

**Review by sumedhbala-delphix — APPROVED** [review]
Ship-it if ab-pre-push passes

**Review by grwilson — APPROVED** [review]

**Comment by grwilson** [comment]
Is mds being mounted explicitly?

**Comment by prakashsurya** [comment]
> Is mds being mounted explicitly?

IIRC, yes, the postgres service will mount it. I'll double check before landing.

**Pull request merged**
