### PR TITLE
DLPX-65674 cron job to clean up 'delphix-upgrade' directory is stale

### PR DESCRIPTION
**Pull request by AdityaPrasad-dlpx**
Changed cron job directory from "/var/log/delphix-upgrade" to "/var/tmp/delphix-upgrade",
testing still tbd

### CODE REVIEW

**Comment by pzakha** [comment]
@prakashsurya Do you know why this keeps failing? It seems like your changes from https://github.com/delphix/delphix-platform/pull/131 are in there.

**Comment by prakashsurya** [comment]
All I know is what can be gathered from the build logs.

**Pull request merged**
