### PR TITLE
DLPX-80957 upgrade failure due to removal of unattended-upgrades package

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
Before landing this, we should better understand why "dcol-dev" is hitting this, but not our regression upgrade tests.

**Comment by prakashsurya** [comment]
Before:
```
root@ip-10-110-226-126:~# sudo apt-get install /delphix-platform-aws_1.0.0-delphix-2022.04.19.21_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'delphix-platform-aws' instead of '/delphix-platform-aws_1.0.0-delphix-2022.04.19.21_amd64.deb'
The following packages will be DOWNGRADED:
  delphix-platform-aws
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 0 B/35.1 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /delphix-platform-aws_1.0.0-delphix-2022.04.19.21_amd64.deb delphix-platform-aws amd64 1.0.0-delphix-2022.04.19.21 [35.1 kB]
dpkg: warning: downgrading delphix-platform-aws from 1.0.0-delphix-2022.04.22.17 to 1.0.0-delphix-2022.04.19.21
(Reading database ... 211620 files and directories currently installed.)
Preparing to unpack .../delphix-platform-aws_1.0.0-delphix-2022.04.19.21_amd64.deb ...
+ case $1 in
+ systemctl disable delphix.target
Removed /etc/systemd/system/default.target.wants/delphix.target.
+ systemctl disable delphix-platform.service
Removed /etc/systemd/system/delphix.target.wants/delphix-platform.service.
+ systemctl disable delphix-rpool-upgrade.service
Removed /etc/systemd/system/delphix.target.wants/delphix-rpool-upgrade.service.
+ rm -f /var/lib/delphix-platform/ansible-done
+ exit 0
Unpacking delphix-platform-aws (1.0.0-delphix-2022.04.19.21) over (1.0.0-delphix-2022.04.22.17) ...
Setting up delphix-platform-aws (1.0.0-delphix-2022.04.19.21) ...
+ case $1 in
+ systemctl disable apt-daily.service
+ systemctl disable apt-daily.timer
+ systemctl disable apt-daily-upgrade.service
+ systemctl disable apt-daily-upgrade.timer
+ systemctl disable unattended-upgrades.service
Failed to disable unit: Unit file unattended-upgrades.service does not exist.
dpkg: error processing package delphix-platform-aws (--configure):
 installed delphix-platform-aws package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 delphix-platform-aws
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

After:
```
root@ip-10-110-226-126:~# sudo apt-get install /delphix-platform-aws_1.0.0-delphix-2022.05.06.18_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'delphix-platform-aws' instead of '/delphix-platform-aws_1.0.0-delphix-2022.05.06.18_amd64.deb'
The following packages will be upgraded:
  delphix-platform-aws
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/35.0 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /delphix-platform-aws_1.0.0-delphix-2022.05.06.18_amd64.deb delphix-platform-aws amd64 1.0.0-delphix-2022.05.06.18 [35.0 kB]
(Reading database ... 211620 files and directories currently installed.)
Preparing to unpack .../delphix-platform-aws_1.0.0-delphix-2022.05.06.18_amd64.deb ...
+ case $1 in
+ systemctl disable delphix.target
Removed /etc/systemd/system/default.target.wants/delphix.target.
+ systemctl disable delphix-platform.service
Removed /etc/systemd/system/delphix.target.wants/delphix-platform.service.
+ systemctl disable delphix-rpool-upgrade.service
Removed /etc/systemd/system/delphix.target.wants/delphix-rpool-upgrade.service.
+ rm -f /var/lib/delphix-platform/ansible-done
+ exit 0
Unpacking delphix-platform-aws (1.0.0-delphix-2022.05.06.18) over (1.0.0-delphix-2022.04.22.17) ...
Setting up delphix-platform-aws (1.0.0-delphix-2022.05.06.18) ...
+ case $1 in
+ systemctl disable apt-daily.service
+ systemctl disable apt-daily.timer
+ systemctl disable apt-daily-upgrade.service
+ systemctl disable apt-daily-upgrade.timer
+ systemctl disable motd-news.service
+ systemctl disable motd-news.timer
+ systemctl enable auditd.service
Synchronizing state of auditd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable auditd
+ systemctl enable delphix.target
Created symlink /etc/systemd/system/default.target.wants/delphix.target → /lib/systemd/system/delphix.target.
+ systemctl enable delphix-platform.service
Created symlink /etc/systemd/system/delphix.target.wants/delphix-platform.service → /lib/systemd/system/delphix-platform.service.
+ systemctl enable delphix-rpool-upgrade.service
Created symlink /etc/systemd/system/delphix.target.wants/delphix-rpool-upgrade.service → /lib/systemd/system/delphix-rpool-upgrade.service.
+ systemctl enable systemd-networkd.service
+ systemctl enable iscsi-name-init.service
+ id -u postgres
++ id -u postgres
+ [[ 65437 -ne 65437 ]]
+ exit 0
```

**Review by sumedhbala-delphix — APPROVED** [review]

**Comment by prakashsurya** [comment]
> Before landing this, we should better understand why "dcol-dev" is hitting this, but not our regression upgrade tests.

We verified our regression tests _are_ hitting this.. the "trick" is just that we need to ensure the "starting version" of the appliance is a version that doesn't have the "unattended-upgrades" package already installed, _and_ the upgrade involves a change in version of the delphix-platform package.. e.g. starting from 6.0.15.0 and upgrading to trunk will satisfy those constraints, and hit this issue.. but starting from 6.0.14.0 and upgrading to trunk will not, as 6.0.14.0 will have the unattended-upgrades package already installed..

**Comment by dbj-delphix** [comment]
This is great @prakashsurya thank you!

**Pull request merged**
