### PR TITLE
CP-4790 Reserve a port for the libs server in delphix-platform

### PR DESCRIPTION
**Pull request by jeffngo**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build was run locally and any changes were pushed
- [ ] Lint has passed locally and any fixes were made for failures

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: CP-4790

We are currently reserving 3 ports for nfsv3, and we would like to add another reserved port for the virtualization sdk libs server.

## What is the new behavior?

Added a reserved port for the libs server in delphix-platform (54046)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4902/

### CODE REVIEW

**Comment by pzakha** [comment]
Changes LGTM. Can you mention the tests that you've run? (Ideally, that would also include a link to `ab-pre-push`)

**Comment by jeffngo** [comment]
> Changes LGTM. Can you mention the tests that you've run? (Ideally, that would also include a link to `ab-pre-push`)

Link to ab-pre-push (also in PR description now): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4902/

**Review by pzakha — APPROVED** [review]
Pending completion of tests

**Review by ravi-cm — APPROVED** [review]
LGTM.

**Pull request merged**
